version: '3.8'
networks:
  dev:
    driver: bridge
services:
  db:
    container_name: users-db
    image: 'ghcr.io/fboulnois/pg_uuidv7:1.6.0'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1.5G
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev
    ports:
      - '5432:5432'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
  bouncer:
    container_name: users-db-bcr
    image: 'bitnami/pgbouncer:latest'
    restart: unless-stopped
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - PGBOUNCER_DATABASE=${POSTGRES_DB}
      - PGBOUNCER_AUTH_TYPE=scram-sha-256
      - PGBOUNCER_AUTH_USER=${POSTGRES_USER}
      - PGBOUNCER_AUTH_QUERY=SELECT usename, passwd FROM pg_shadow WHERE usename=$1
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1.5G
    networks:
      - dev
    ports:
      - '6432:6432'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    depends_on:
      db:
        condition: service_healthy
  cache:
    container_name: users-cache
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1.5G
    command: ['--requirepass', '${CACHE_PASSWORD}']
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    networks:
      - dev
    environment:
      - CACHE_PASSWORD=${CACHE_PASSWORD}
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${CACHE_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
  api:
    container_name: users-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1.5G
    ports:
      - '${PORT}:8080'
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - POSTGRES_HOST=bouncer
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=6432
      - COOKIE_SECRET=${COOKIE_SECRET}
      - CACHE_HOST=cache
      - CACHE_USER=default
      - CACHE_PASSWORD=${CACHE_PASSWORD}
      - CACHE_PORT=6379
      - BASE_URL=${BASE_URL}
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    secrets:
      - public_key
      - private_key

secrets:
  public_key:
    file: ./src/secrets/public.pem
  private_key:
    file: ./src/secrets/private.pem
volumes:
  pgdata:
  dragonflydata:
