name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Prepare JWT keys
        run: |
          mkdir -p ./src/secrets
          echo "$PRIVATE_KEY_B64" | base64 -d > ./src/secrets/private.pem
          echo "$PUBLIC_KEY_B64" | base64 -d > ./src/secrets/public.pem
        env:
          PRIVATE_KEY_B64: ${{ secrets.PRIVATE_KEY_B64 }}
          PUBLIC_KEY_B64: ${{ secrets.PUBLIC_KEY_B64 }}

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} <<EOF
            cd ./services/${{ github.event.repository.name }}
            git reset --hard
            git pull origin main
            docker compose down --volumes
            docker compose up -d --build
          EOF
